<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-MUPOVES" failures="1" tests="1" name="com.qa.api.gorest.tests.UpdateUserTest" time="7.391" errors="0" timestamp="12 Jan 2022 08:08:41 GMT" skipped="0">
  <testcase classname="com.qa.api.gorest.tests.UpdateUserTest" name="updateUser_createAndThenDeleteAPITest" time="7.391">
    <failure message="expected [Siddhi91932NEW] but found [Siddhi91932NEWFAIL]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Siddhi91932NEW] but found [Siddhi91932NEWFAIL]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.qa.api.gorest.tests.UpdateUserTest.updateUser_createAndThenDeleteAPITest(UpdateUserTest.java:94)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
    </failure>
  </testcase> <!-- updateUser_createAndThenDeleteAPITest -->
</testsuite> <!-- com.qa.api.gorest.tests.UpdateUserTest -->
